import { useEffect, useMemo, useState } from "react";
import RoleLayout from "../../components/RoleLayout";
import { getMyWorkerMedicalRecords } from "../../services/workerService";
import { getApiError } from "../../services/api";
import { downloadMedicalAttachment, openMedicalAttachment } from "../../services/medicalService";

const formatDate = (value) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Date unavailable" : new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(date); };
const size = (bytes = 0) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;

const Documents = () => {
  const [documents, setDocuments] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [preview, setPreview] = useState(null); const [typeFilter, setTypeFilter] = useState("ALL");
  useEffect(() => { getMyWorkerMedicalRecords().then((records) => setDocuments((Array.isArray(records) ? records : []).flatMap((record) => (record.attachments || []).map((attachment) => ({ ...attachment, visitDate: record.visitDate, hospitalName: record.hospitalName, doctorName: record.doctorName }))))).catch((err) => setError(getApiError(err, "Unable to load your medical documents."))).finally(() => setLoading(false)); }, []);
  const view = async (document) => { try { setError(""); const url = await openMedicalAttachment(document); if (document.mimeType?.startsWith("image/")) setPreview({ url, name: document.fileName }); else window.open(url, "_blank", "noopener,noreferrer"); } catch (err) { setError(getApiError(err, "Unable to open document.")); } };
  const close = () => { if (preview?.url) URL.revokeObjectURL(preview.url); setPreview(null); };
  const types = useMemo(() => [...new Set(documents.map((item) => item.mimeType).filter(Boolean))], [documents]);
  const filtered = useMemo(() => typeFilter === "ALL" ? documents : documents.filter((item) => item.mimeType === typeFilter), [documents, typeFilter]);
  if (loading) return <RoleLayout title="Documents"><div className="loading-card">Loading your medical documents…</div></RoleLayout>;
  return <RoleLayout title="Medical documents" description="Documents attached to your authorized clinical records, available for secure viewing or download.">
    {error && <div className="alert error" role="alert">{error}</div>}
    <div className="worker-page-toolbar"><div><span className="eyebrow">Clinical documents</span><h2>{filtered.length} file{filtered.length === 1 ? "" : "s"}</h2><p>Documents are provided for reference and remain read-only in your worker portal.</p></div><label className="field compact-filter"><span>File type</span><select className="select compact-select" value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)}><option value="ALL">All file types</option>{types.map((type) => <option key={type} value={type}>{type.replace("application/", "").replace("image/", "").toUpperCase()}</option>)}</select></label></div>
    {filtered.length === 0 ? <div className="empty-state-card worker-empty-state"><span className="worker-empty-large">□</span><div><h3>No medical documents</h3><p>{documents.length ? "No documents match the selected file type." : "Documents uploaded by authorized healthcare staff will appear here."}</p>{typeFilter !== "ALL" && <button className="button button-secondary" type="button" onClick={() => setTypeFilter("ALL")}>Show all files</button>}</div></div> : <div className="worker-document-grid">{filtered.map((item) => <article className="worker-document-card" key={`${item.id}-${item.visitDate}`}><div className="worker-document-icon">{item.mimeType?.startsWith("image/") ? "IMG" : "PDF"}</div><div className="worker-document-main"><div className="worker-document-heading"><div><span className="eyebrow">{formatDate(item.visitDate)}</span><h3>{item.fileName}</h3></div><span className="status-badge status-active">SECURE</span></div><p>From {item.hospitalName || "hospital record"} · {item.doctorName || "authorized clinician"}</p><div className="worker-document-meta"><span>{item.mimeType || "Unknown type"}</span><span>{size(item.fileSize)}</span><span>Uploaded {formatDate(item.createdAt)}</span></div><div className="worker-document-actions"><button className="button button-secondary" type="button" onClick={() => view(item)}><span aria-hidden="true">↗</span> View</button><button className="button button-ghost worker-icon-button" type="button" onClick={() => downloadMedicalAttachment(item)} aria-label={`Download ${item.fileName}`} title="Download"><span aria-hidden="true">↓</span></button></div></div></article>)}</div>}
    {preview && <div className="modal-backdrop" role="presentation" onClick={close}><div className="modal modal-large" role="dialog" aria-modal="true" aria-labelledby="worker-document-preview" onClick={(event) => event.stopPropagation()}><div className="modal-header"><div><span className="eyebrow">Document preview</span><h2 id="worker-document-preview">{preview.name}</h2></div><button className="modal-close" type="button" onClick={close} aria-label="Close preview">×</button></div><img src={preview.url} alt={preview.name} style={{ maxWidth: "100%", maxHeight: "70vh", objectFit: "contain" }} /></div></div>}
  </RoleLayout>;
};
export default Documents;
