import { useEffect, useMemo, useState } from "react";
import RoleLayout from "../../components/RoleLayout";
import { getMyWorkerMedicalRecords } from "../../services/workerService";
import { getApiError } from "../../services/api";
import { downloadMedicalAttachment, openMedicalAttachment } from "../../services/medicalService";

const formatDate = (value) => { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(date); };
const formatDateTime = (value) => { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(date); };
const fileSize = (bytes = 0) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / (1024 * 1024)).toFixed(1)} MB`;

const MedicalHistory = () => {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(""); const [hospitalFilter, setHospitalFilter] = useState("ALL"); const [selectedRecord, setSelectedRecord] = useState(null); const [preview, setPreview] = useState(null);
  const load = async (refresh = false) => { try { setError(""); if (refresh) setRefreshing(true); else setLoading(true); const data = await getMyWorkerMedicalRecords(); setRecords(Array.isArray(data) ? data : []); } catch (err) { setError(getApiError(err, "Unable to load medical history.")); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { load(); }, []);
  const hospitals = useMemo(() => [...new Set(records.map((r) => r.hospitalName).filter(Boolean))], [records]);
  const filtered = useMemo(() => hospitalFilter === "ALL" ? records : records.filter((r) => r.hospitalName === hospitalFilter), [records, hospitalFilter]);
  const openAttachment = async (attachment) => { try { setError(""); const url = await openMedicalAttachment(attachment); if (attachment.mimeType?.startsWith("image/")) setPreview({ url, name: attachment.fileName }); else window.open(url, "_blank", "noopener,noreferrer"); } catch (err) { setError(getApiError(err, "Unable to open document.")); } };
  const closePreview = () => { if (preview?.url) URL.revokeObjectURL(preview.url); setPreview(null); };
  if (loading) return <RoleLayout title="Medical history"><div className="loading-card">Loading medical history…</div></RoleLayout>;
  return <RoleLayout title="Medical history" description="Visits and treatment history." actions={[{ label: refreshing ? "Refreshing…" : "Refresh", onClick: () => load(true), variant: "secondary", disabled: refreshing }]}>
    {error && <div className="alert error" role="alert">{error}</div>}
    <div className="worker-page-toolbar"><div><span className="eyebrow">Visits</span><h2>{filtered.length} record{filtered.length === 1 ? "" : "s"}</h2></div><label className="field compact-filter"><span>Hospital</span><select className="select compact-select" value={hospitalFilter} onChange={(e) => setHospitalFilter(e.target.value)}><option value="ALL">All hospitals</option>{hospitals.map((h) => <option key={h} value={h}>{h}</option>)}</select></label></div>
    {filtered.length === 0 ? <div className="empty-state-card worker-empty-state"><div><h3>No medical records</h3><p>{records.length ? "No records for this hospital." : "Your visits will appear here."}</p>{hospitalFilter !== "ALL" && <button className="button button-secondary" type="button" onClick={() => setHospitalFilter("ALL")}>Show all hospitals</button>}</div></div> : <div className="record-timeline" aria-label="Medical history">{filtered.map((record) => <article className="medical-record-card" key={record.id}>
      <div className="record-date"><strong>{formatDate(record.visitDate)}</strong><span>Visit</span></div>
      <div className="record-body"><div className="record-heading"><div><span className="status-badge status-active">{record.hospitalName || "Hospital"}</span><h3>{record.diagnosis || "Clinical record"}</h3><p>Dr. {record.doctorName || "—"}</p></div><button className="button button-ghost button-small" type="button" onClick={() => setSelectedRecord(record)}>View</button></div>
      <div className="record-fields"><div><small>Symptoms</small><p>{record.symptoms || "—"}</p></div><div><small>Treatment</small><p>{record.treatment || "—"}</p></div><div><small>Notes</small><p>{record.notes || "—"}</p></div></div>
      <div className="prescription-section"><div className="prescription-header"><h4>Prescriptions</h4><span className="muted-note">{record.prescriptions?.length || 0}</span></div>{record.prescriptions?.length ? <div className="prescription-list">{record.prescriptions.map((item) => <div className="prescription-item" key={item.id}><div><strong>{item.medicineName}</strong><span>{[item.dosage, item.frequency, item.duration].filter(Boolean).join(" · ") || "—"}</span>{item.instructions && <small>{item.instructions}</small>}</div></div>)}</div> : <p className="muted-note">None</p>}</div>
      <div className="prescription-section"><div className="prescription-header"><h4>Documents</h4><span className="muted-note">{record.attachments?.length || 0}</span></div>{record.attachments?.length ? <div className="prescription-list">{record.attachments.map((item) => <div className="prescription-item" key={item.id}><div><strong>{item.fileName}</strong><span>{item.mimeType || "File"} · {fileSize(item.fileSize)}</span></div><div><button className="button button-ghost button-small" type="button" onClick={() => openAttachment(item)}>View</button><button className="button button-ghost button-small" type="button" onClick={() => downloadMedicalAttachment(item)}>Download</button></div></div>)}</div> : <p className="muted-note">None</p>}</div>
      </div></article>)}</div>}
    {selectedRecord && <div className="modal-backdrop" role="presentation"><div className="modal modal-large" role="dialog" aria-modal="true"><div className="modal-header"><div><span className="eyebrow">Visit</span><h2>{selectedRecord.diagnosis || "Clinical record"}</h2><p>{selectedRecord.hospitalName || "Hospital"} · Dr. {selectedRecord.doctorName || "—"}</p></div><button className="modal-close" type="button" onClick={() => setSelectedRecord(null)} aria-label="Close">×</button></div><div className="record-detail-summary"><div><small>Visit date</small><strong>{formatDate(selectedRecord.visitDate)}</strong></div><div><small>Started</small><strong>{formatDateTime(selectedRecord.startedAt)}</strong></div></div><div className="record-fields detail-fields"><div><small>Symptoms</small><p>{selectedRecord.symptoms || "—"}</p></div><div><small>Diagnosis</small><p>{selectedRecord.diagnosis || "—"}</p></div><div><small>Treatment</small><p>{selectedRecord.treatment || "—"}</p></div><div><small>Notes</small><p>{selectedRecord.notes || "—"}</p></div></div></div></div>}
    {preview && <div className="modal-backdrop" role="presentation" onClick={closePreview}><div className="modal modal-large" role="dialog" aria-modal="true" onClick={(e) => e.stopPropagation()}><div className="modal-header"><h2>{preview.name}</h2><button className="modal-close" type="button" onClick={closePreview} aria-label="Close">×</button></div><img src={preview.url} alt={preview.name} style={{ maxWidth: "100%", maxHeight: "70vh", objectFit: "contain" }} /></div></div>}
  </RoleLayout>;
};
export default MedicalHistory;
