import { useEffect, useState } from "react";
import { getMedicalRecords, createMedicalRecord, updateMedicalRecord, deleteMedicalRecord, createPrescription, updatePrescription, deletePrescription } from "../../services/MedicalService";

const blankRecord = { visitDate: "", symptoms: "", diagnosis: "", treatment: "", notes: "" };
const blankPrescription = { medicineName: "", dosage: "", frequency: "", duration: "", instructions: "" };

const MedicalRecords = ({ workerId }) => {
  const [records, setRecords] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [recordForm, setRecordForm] = useState(blankRecord); const [prescriptionForm, setPrescriptionForm] = useState(blankPrescription); const [recordTarget, setRecordTarget] = useState(null); const [prescriptionTarget, setPrescriptionTarget] = useState(null); const [showRecordForm, setShowRecordForm] = useState(false); const [prescriptionRecordId, setPrescriptionRecordId] = useState(null);
  const loadRecords = async () => { try { setError(""); setRecords(await getMedicalRecords(workerId)); } catch (err) { setError(err.response?.data?.error || "Unable to load medical records."); } finally { setLoading(false); } };
  useEffect(() => { loadRecords(); }, [workerId]);
  const submitRecord = async (e) => { e.preventDefault(); try { if (recordTarget) await updateMedicalRecord(recordTarget.id, recordForm); else await createMedicalRecord(workerId, recordForm); setRecordForm(blankRecord); setRecordTarget(null); setShowRecordForm(false); await loadRecords(); } catch (err) { setError(err.response?.data?.error || "Unable to save medical record."); } };
  const submitPrescription = async (e) => { e.preventDefault(); try { if (prescriptionTarget) await updatePrescription(prescriptionTarget.id, prescriptionForm); else await createPrescription(prescriptionRecordId, prescriptionForm); setPrescriptionForm(blankPrescription); setPrescriptionTarget(null); setPrescriptionRecordId(null); await loadRecords(); } catch (err) { setError(err.response?.data?.error || "Unable to save prescription."); } };
  const editRecord = (record) => { setRecordTarget(record); setRecordForm({ visitDate: record.visitDate || "", symptoms: record.symptoms || "", diagnosis: record.diagnosis || "", treatment: record.treatment || "", notes: record.notes || "" }); setShowRecordForm(true); };
  const editPrescription = (item) => { setPrescriptionTarget(item); setPrescriptionForm({ medicineName: item.medicineName || "", dosage: item.dosage || "", frequency: item.frequency || "", duration: item.duration || "", instructions: item.instructions || "" }); };
  const remove = async (action, message) => { if (!window.confirm(message)) return; try { await action(); await loadRecords(); } catch (err) { setError(err.response?.data?.error || "Unable to complete the action."); } };

  if (loading) return <div className="loading-card">Loading medical history...</div>;
  return <section className="medical-records-section">
    <div className="section-toolbar"><div><span className="eyebrow">Clinical history</span><h2>Medical records</h2><p>{records.length} recorded visit{records.length === 1 ? "" : "s"}</p></div><button className="button button-primary" onClick={() => { setRecordTarget(null); setRecordForm(blankRecord); setShowRecordForm(true); }}>+ Add record</button></div>
    {error && <div className="alert error">{error}</div>}
    {records.length === 0 ? <div className="empty-state-card"><span className="empty-icon">+</span><h3>No medical records yet</h3><p>Add the first clinical visit for this worker.</p></div> : <div className="record-timeline">{records.map((record) => <article className="medical-record-card" key={record.id}><div className="record-date"><strong>{record.visitDate || "—"}</strong><span>Visit</span></div><div className="record-body"><div className="record-heading"><div><span className="status-badge status-active">Diagnosis</span><h3>{record.diagnosis}</h3></div><div className="row-actions"><button className="button button-ghost button-small" onClick={() => editRecord(record)}>Edit</button><button className="button button-ghost button-small" onClick={() => remove(() => deleteMedicalRecord(record.id), "Delete this medical record and its prescriptions?")}>Delete</button></div></div><div className="record-fields"><div><small>Symptoms</small><p>{record.symptoms || "—"}</p></div><div><small>Treatment</small><p>{record.treatment || "—"}</p></div><div><small>Notes</small><p>{record.notes || "—"}</p></div></div><div className="prescription-section"><div className="prescription-header"><h4>Prescriptions</h4><button className="button button-secondary button-small" onClick={() => { setPrescriptionTarget(null); setPrescriptionForm(blankPrescription); setPrescriptionRecordId(record.id); }}>+ Add prescription</button></div>{record.prescriptions?.length ? <div className="prescription-list">{record.prescriptions.map((item) => <div className="prescription-item" key={item.id}><div><strong>{item.medicineName}</strong><span>{[item.dosage, item.frequency, item.duration].filter(Boolean).join(" · ") || "No dosage details"}</span>{item.instructions && <small>{item.instructions}</small>}</div><div className="row-actions"><button className="button button-ghost button-small" onClick={() => editPrescription(item)}>Edit</button><button className="button button-ghost button-small" onClick={() => remove(() => deletePrescription(item.id), "Delete this prescription?")}>Delete</button></div></div>)}</div> : <p className="muted-note">No prescriptions for this visit.</p>}</div></div></article>)}</div>}

    {showRecordForm && <div className="modal-backdrop"><div className="modal modal-large"><div className="modal-header"><div><span className="eyebrow">{recordTarget ? "Update visit" : "New visit"}</span><h2>{recordTarget ? "Edit medical record" : "Add medical record"}</h2></div><button className="modal-close" onClick={() => setShowRecordForm(false)}>×</button></div><form onSubmit={submitRecord} className="form-grid"><div className="field"><label>Visit date</label><input className="input" type="date" value={recordForm.visitDate} onChange={(e) => setRecordForm({ ...recordForm, visitDate: e.target.value })} required /></div><div className="field"><label>Diagnosis</label><input className="input" value={recordForm.diagnosis} onChange={(e) => setRecordForm({ ...recordForm, diagnosis: e.target.value })} required /></div><div className="field full"><label>Symptoms</label><textarea className="textarea" value={recordForm.symptoms} onChange={(e) => setRecordForm({ ...recordForm, symptoms: e.target.value })} /></div><div className="field full"><label>Treatment</label><textarea className="textarea" value={recordForm.treatment} onChange={(e) => setRecordForm({ ...recordForm, treatment: e.target.value })} /></div><div className="field full"><label>Notes</label><textarea className="textarea" value={recordForm.notes} onChange={(e) => setRecordForm({ ...recordForm, notes: e.target.value })} /></div><div className="field full"><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => setShowRecordForm(false)}>Cancel</button><button className="button button-primary">Save record</button></div></div></form></div></div>}
    {(prescriptionRecordId || prescriptionTarget) && <div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><span className="eyebrow">Medication</span><h2>{prescriptionTarget ? "Edit prescription" : "Add prescription"}</h2></div><button className="modal-close" onClick={() => { setPrescriptionRecordId(null); setPrescriptionTarget(null); }}>×</button></div><form onSubmit={submitPrescription} className="form-grid"><div className="field full"><label>Medicine name</label><input className="input" value={prescriptionForm.medicineName} onChange={(e) => setPrescriptionForm({ ...prescriptionForm, medicineName: e.target.value })} required /></div><div className="field"><label>Dosage</label><input className="input" value={prescriptionForm.dosage} onChange={(e) => setPrescriptionForm({ ...prescriptionForm, dosage: e.target.value })} /></div><div className="field"><label>Frequency</label><input className="input" value={prescriptionForm.frequency} onChange={(e) => setPrescriptionForm({ ...prescriptionForm, frequency: e.target.value })} /></div><div className="field"><label>Duration</label><input className="input" value={prescriptionForm.duration} onChange={(e) => setPrescriptionForm({ ...prescriptionForm, duration: e.target.value })} /></div><div className="field full"><label>Instructions</label><textarea className="textarea" value={prescriptionForm.instructions} onChange={(e) => setPrescriptionForm({ ...prescriptionForm, instructions: e.target.value })} /></div><div className="field full"><div className="modal-actions"><button type="button" className="button button-secondary" onClick={() => { setPrescriptionRecordId(null); setPrescriptionTarget(null); }}>Cancel</button><button className="button button-primary">Save prescription</button></div></div></form></div></div>}
  </section>;
};
export default MedicalRecords;
